module.exports = {
  enjoying: [
    { name: "HTML5", url: "https://en.wikipedia.org/wiki/HTML" },
    { name: "CSS3", url: "https://en.wikipedia.org/wiki/CSS" },
    { name: "JavaScript", url: "https://en.wikipedia.org/wiki/JavaScript" },
    { name: "React", url: "https://react.dev/" },
    { name: "Next.js", url: "https://nextjs.org/" },
    { name: "tailwindcss", url: "https://tailwindcss.com/" },
    { name: "Vercel", url: "https://vercel.com/" },
    { name: "Sanity", url: "https://www.sanity.io/" },
    { name: "Git", url: "https://git-scm.com/" },
    { name: "GitHub", url: "https://github.com/" },
    { name: "Codeberg", url: "https://codeberg.org/" },
    { name: "Linux", url: "https://www.linux.org/" },
    { name: "ArchLinux", url: "https://archlinux.org/" },
    { name: "EndeavourOS", url: "https://endeavouros.com/" },
    { name: "Python", url: "https://www.python.org/" },
    {
      name: "C",
      url: "https://en.wikipedia.org/wiki/C_(programming_language)",
    },
    { name: "11ty", url: "https://www.11ty.dev/" },
    { name: "htmx", url: "https://htmx.org/" },
  ],
  exploring: [
    { name: "Upstash", url: "https://upstash.com/" },
    { name: "hyperscript", url: "https://hyperscript.org/" },
    { name: "Contentful", url: "https://www.contentful.com/" },
    { name: "MongoDB", url: "https://www.mongodb.com/" },
    { name: "Docker", url: "https://www.docker.com/" },
    { name: "Svelte", url: "https://svelte.dev/" },
    { name: "Firebase", url: "https://firebase.google.com/" },
    { name: "Strapi", url: "https://strapi.io/" },
    { name: "Storyblok", url: "https://www.storyblok.com/" },
  ],
};
