module.exports = {
  enjoying: [
    { name: "HTML5", url: "https://en.wikipedia.org/wiki/HTML" },
    { name: "CSS3", url: "https://en.wikipedia.org/wiki/CSS" },
    { name: "JavaScript", url: "https://en.wikipedia.org/wiki/JavaScript" },
    { name: "React", url: "https://react.dev/" },
    { name: "Next.js", url: "https://nextjs.org/" },
    { name: "tailwindcss", url: "https://tailwindcss.com/" },
    { name: "Vercel", url: "https://vercel.com/" },
    { name: "Sanity", url: "https://www.sanity.io/" },
    { name: "Git", url: "https://git-scm.com/" },
    { name: "GitHub", url: "https://github.com/" },
    { name: "Codeberg", url: "https://codeberg.org/" },
    { name: "Linux", url: "https://www.linux.org/" },
    { name: "ArchLinux", url: "https://archlinux.org/" },
    { name: "EndeavourOS", url: "https://endeavouros.com/" },
    { name: "Python", url: "https://www.python.org/" },
    {
      name: "C",
      url: "https://en.wikipedia.org/wiki/C_(programming_language)",
    },
    { name: "11ty", url: "https://www.11ty.dev/" },
  ],
  exploring: [
    { name: "Docker", url: "" },
    { name: "AWS", url: "" },
    { name: "GCS", url: "" },
    { name: "Svelte", url: "" },
    { name: "MongoDB", url: "" },
    { name: "Firebase", url: "" },
    { name: "Upstash", url: "" },
    { name: "Kubernetes", url: "" },
    { name: "Strapi", url: "" },
    { name: "Storyblok", url: "" },
    { name: "htmx", url: "" },
    { name: "hyperscript", url: "" },
  ],
};
